{
    'name': 'Tienda Multi Agente Crumges',
    'version': '18.0.1.0.0',
    'category': 'Sales/Sales',
    'summary': 'Permite a agentes comprar en nombre de clientes vía Portal o Backend.',
    'author': 'Crumges',
    'website': 'https://crumges.com',
    'license': 'LGPL-3',
    'maintainers': ['Crumges'],
    'depends': [
        'sale',
        'website_sale',
        'base',
        'account',
    ],
    'data': [
        'data/website_menu_data.xml',
        'views/website_navbar_inherit.xml',
        'views/res_partner_views.xml',
        'views/sale_order_views.xml',
        'views/account_move_views.xml',
        'views/agent_shop_template.xml',
        'views/sale_order_cart_template.xml',
        'views/sale_order_portal_template.xml',
        'views/invoice_report_template.xml',
        'views/sale_order_report_template.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'images': ['static/description/icon.png'],
}